global:
  scrape_interval: 5s

scrape_configs:
  - job_name: kafka
    static_configs:
      - targets:
        - broker-1:7071
        - broker-2:7071
        - broker-3:7071
        - broker-4:7071
